### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict

### ISSUE THREAD

**Issue by programmerZe** [liruiwen/TransCAM#1]
Hi! I got an error when I trained the conformer classifier with the command `python train_TransCAM.py --weights pretrain/Conformer_small_patch32.pth`.

Removing key trans_cls_head.weight from pretrained checkpoint
Removing key trans_cls_head.bias from pretrained checkpoint
Removing key conv_cls_head.weight from pretrained checkpoint
Removing key conv_cls_head.bias from pretrained checkpoint
Traceback (most recent call last):
  File "train_TransCAM.py", line 77, in <module>
    model.load_state_dict(model_dict)
  File "/opt/zy/anaconda3/envs/cam/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Net_sm:
        size mismatch for trans_patch_conv.weight: copying a param with shape torch.Size([384, 64, 8, 8]) from checkpoint, the shape in current model is torch.Size([384, 64, 4, 4]).

Is there anything wrong with my running command or pretrained model? I downloaded Conformer-S pretrained weights from https://pan.baidu.com/s/1pum_kOOwQYn404ZeGzjMlg and put it into the folder `pretrain`.

**Comment by programmerZe** [comment]
The download link of the pretrained model is from https://github.com/pengzhiliang/Conformer/blob/main/mmdetection/README.md

**Comment by liruiwen** [comment]
Thanks for your attention to our work. We used pretrained Conformer-S with patch size 16. The download link can be found here: https://github.com/pengzhiliang/Conformer#model-zoo.

**Comment by programmerZe** [comment]
Yes it works. Thanks you!
