### ISSUE TITLE
it takes too much time in the 'infer_TransCAM.py'

### ISSUE THREAD

**Issue by YuYue26** [liruiwen/TransCAM#2]
i take about 4.4hours to finish the infer with train_aug.txt, which is include 10582 images.
is something wrong or i can do to improve this?

**Comment by liruiwen** [comment]
Hi, thanks for your attention to our work. You could do multi-processing as in: https://github.com/YudeWang/SEAM/blob/3212261b9d008581576b8b5429e32413d892c10b/infer_SEAM.py#L67. For the ease of debugging and the limitation of computing resources, I didn't integrate that code.
