### ISSUE TITLE
the result of TransCAM step can't be reproduce?

### ISSUE THREAD

**Issue by YuYue26** [liruiwen/TransCAM#3]
the MIoU score of TransCAM step is 64.85% by evalute the train.txt

and i train the train_aug.txt with your parameter including lr=5e-5, max epoch=20, wt_dec=5e-4, batch_size=8, 

but i got the result 63.46%, i think there must be something different from your work, could you tell me how can i do to follow the accurracy in this paper

ps: my environment is a single 3090 and python 3.7

**Comment by liruiwen** [comment]
I think the result is OK. I would suggest train with a different random seed. Based on my experience, the mIoU could vary around 2% for different seeds.

**Comment by YuYue26** [comment]
thanks
