### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'VOCdevkit/VOC2012/ImageSets/Segmentation/trainaug.txt'

### ISSUE THREAD

**Issue by cny1234** [liruiwen/TransCAM#5]
你好，我在执行python train_deeplab.py这步的时候出现没有trainaug.txt文件这个路径，我在官网上下载是没有这个文件的，可以告诉我在哪里能下载这个文件吗

**Comment by liruiwen** [comment]
你好，可以根据https://github.com/liruiwen/TransCAM/blob/main/voc12/train_aug.txt 写个简单脚本输出跟VOCdevkit相同格式
