### ISSUE TITLE
How to Visualize Attention？

### ISSUE THREAD

**Issue by RongcanChen** [liruiwen/TransCAM#7]
How to visualize attention? Like Figure 3 in the paper.

**Comment by liruiwen** [comment]
> How to visualize attention? Like Figure 3 in the paper.

You can use matplotlib to plot the attention weights in https://github.com/liruiwen/TransCAM/blob/4ffe69382e4cfd87e82d76f9f5f36f703597d56d/network/conformer.py#L462C9-L462C28

**Comment by RongcanChen** [comment]
Thanks for your reply, can you provide the specific code?

**Comment by liruiwen** [comment]
> Thanks for your reply, can you provide the specific code?

[draw.zip](https://github.com/liruiwen/TransCAM/files/14830825/draw.zip)
You can save the attention weights as .npy, and you may modify this code to do the visualization.
